// find the icons you want at 
// https://materialdesignicons.com/
// add them here.
// For your own sake, respect the convention defined here!
// Name the icon FOR USAGE. For example, if you need an icon for "Like",
// and the icon is named "HeartFull", do:
// export { default as IconLike } from 'vue-material-design-icons/HeartFull' 
// then use it as <icon-like/>. If you need the same icon for a different usage,
// just import it again
export { default as IconMastodon } from 'vue-material-design-icons/Mastodon'
export { default as IconTwitter } from 'vue-material-design-icons/Twitter'
export { default as IconGitlab } from 'vue-material-design-icons/Gitlab'
export { default as IconReddit } from 'vue-material-design-icons/Reddit'
export { default as IconMatrix } from 'vue-material-design-icons/ChatProcessing'
export { default as IconEmail } from 'vue-material-design-icons/Email'
export { default as IconCodesandbox } from 'vue-material-design-icons/CodeBracesBox'
export { default as IconGithub } from 'vue-material-design-icons/GithubCircle'
export { default as IconTelegram } from 'vue-material-design-icons/Telegram'
export { default as IconSkype } from 'vue-material-design-icons/Skype'
export { default as IconCodepen } from 'vue-material-design-icons/Codepen'
export { default as IconKeybase } from 'vue-material-design-icons/PoundBox'
export { default as IconLinkedin } from 'vue-material-design-icons/Linkedin'

export { default as IconOffice } from 'vue-material-design-icons/Briefcase'
export { default as IconFamily } from 'vue-material-design-icons/AccountGroup'
export { default as IconActivist } from 'vue-material-design-icons/Incognito'
export { default as IconJournalist } from 'vue-material-design-icons/Newspaper'
export { default as IconPersonal } from 'vue-material-design-icons/Account'

export { default as IconNotFound } from 'vue-material-design-icons/Alert'

export { default as IconLinux } from 'vue-material-design-icons/Linux'
export { default as IconMac } from 'vue-material-design-icons/Apple'
export { default as IconWindows } from 'vue-material-design-icons/Windows'
export { default as IconGoogle } from 'vue-material-design-icons/GooglePlay'
export { default as IconFDroid } from 'vue-material-design-icons/AndroidDebugBridge'
export { default as IconIos } from 'vue-material-design-icons/AppleIos'
export { default as IconWeb } from 'vue-material-design-icons/Web'
export { default as IconFirefox } from 'vue-material-design-icons/Firefox'
export { default as IconChrome } from 'vue-material-design-icons/GoogleChrome'
export { default as IconOpera } from 'vue-material-design-icons/Opera'
export { default as IconPocketBook } from 'vue-material-design-icons/BookOpenPageVariant'
export { default as IconKobo } from 'vue-material-design-icons/BookOpenPageVariant'
export { default as IconKindle } from 'vue-material-design-icons/BookOpenPageVariant'

export { default as IconOsi } from 'vue-material-design-icons/OpenSourceInitiative'
export { default as IconPaid } from 'vue-material-design-icons/CurrencyUsd'
export { default as IconExternal } from 'vue-material-design-icons/OpenInNew'
export { default as IconRss } from 'vue-material-design-icons/Rss'
export { default as IconAtom } from 'vue-material-design-icons/Atom'
export { default as IconGit } from 'vue-material-design-icons/Git'
export { default as IconNoGood } from 'vue-material-design-icons/Cancel'
export { default as IconOk } from 'vue-material-design-icons/CheckBold'

export { default as IconHome } from 'vue-material-design-icons/Home'
export { default as IconBlog } from 'vue-material-design-icons/NewspaperVariant'

export { default as IconFreeMe } from 'vue-material-design-icons/Balloon'
export { default as IconFreeMe2 } from 'vue-material-design-icons/GridLarge'

export { default as IconHighlightEmail } from 'vue-material-design-icons/EmailOutline'
export { default as IconHighlightEmail2 } from 'vue-material-design-icons/Lock'
export { default as IconHighlightStorage } from 'vue-material-design-icons/CloudOutline'
export { default as IconHighlightStorage2 } from 'vue-material-design-icons/Sync'
export { default as IconHighlightOffice } from 'vue-material-design-icons/ClipboardListOutline'
export { default as IconHighlightOffice2 } from 'vue-material-design-icons/CalendarClock'
export { default as IconHighlightCommunication } from 'vue-material-design-icons/ShieldAccountOutline'
export { default as IconHighlightCommunication2 } from 'vue-material-design-icons/ChatOutline'
export { default as IconHighlightMuchMore } from 'vue-material-design-icons/GiftOutline'
export { default as IconHighlightMuchMore2 } from 'vue-material-design-icons/StarOutline'
export { default as IconReadMore } from 'vue-material-design-icons/ArrowRight'
export { default as IconGmail } from 'vue-material-design-icons/Gmail'
export { default as IconGoogleDocs } from 'vue-material-design-icons/FileDocument'
export { default as IconFeature2FA } from 'vue-material-design-icons/TwoFactorAuthentication'
export { default as IconFeatureBookmarksSync } from 'vue-material-design-icons/Bookmark'
export { default as IconFeatureCalendar } from 'vue-material-design-icons/Calendar'
export { default as IconFeatureCollaborativeBudgetManagement } from 'vue-material-design-icons/Wallet'
export { default as IconFeatureContactsSync } from 'vue-material-design-icons/Contacts'
export { default as IconFeatureDecentralizedChat } from 'vue-material-design-icons/ChatProcessing'
export { default as IconFeatureEbookLibrary } from 'vue-material-design-icons/Bookshelf'
export { default as IconFeatureEmailClient } from 'vue-material-design-icons/EmailOutline'
export { default as IconFeatureEmailServer } from 'vue-material-design-icons/MailboxOutline'
export { default as IconFeatureFederatedSocialNetwork } from 'vue-material-design-icons/Webhook'
export { default as IconFeatureFileStorageAndSyncing } from 'vue-material-design-icons/CloudUpload'
export { default as IconFeatureKanbanBoard } from 'vue-material-design-icons/FormatColumns'
export { default as IconFeatureMaps } from 'vue-material-design-icons/MapSearchOutline'
export { default as IconFeatureMeetingsScheduler } from 'vue-material-design-icons/CalendarClock'
export { default as IconFeatureMindMap } from 'vue-material-design-icons/GraphOutline'
export { default as IconFeatureNewsReader } from 'vue-material-design-icons/NewspaperVariantMultipleOutline'
export { default as IconFeatureNewsletterManagement } from 'vue-material-design-icons/EmailNewsletter'
export { default as IconFeatureNotes } from 'vue-material-design-icons/Text'
export { default as IconFeaturePasswordManager } from 'vue-material-design-icons/KeyOutline'
export { default as IconFeaturePhoneTracking } from 'vue-material-design-icons/Radar'
export { default as IconFeaturePollsAndForms } from 'vue-material-design-icons/ClipboardAccountOutline'
export { default as IconFeatureSelfDestructiveMessages } from 'vue-material-design-icons/Incognito'
export { default as IconFeatureSimpleWebsitePublishing } from 'vue-material-design-icons/FountainPenTip'
export { default as IconFeatureSmsSync } from 'vue-material-design-icons/BackupRestore'
export { default as IconFeatureTasks } from 'vue-material-design-icons/FormatListCheckbox'
export { default as IconFeatureVideoCall } from 'vue-material-design-icons/VideoWirelessOutline'
export { default as IconFeatureServicesIntegration } from 'vue-material-design-icons/Pipe'
export { default as IconFeatureStreamingService } from 'vue-material-design-icons/ChatProcessing'
export { default as IconFeatureVirtualAndroid } from 'vue-material-design-icons/ChatProcessing'
export { default as IconFeatureVpn } from 'vue-material-design-icons/Vpn'
export { default as IconFeatureWorkflowAutomation } from 'vue-material-design-icons/StateMachine'